name: Build and Test .NET

on:
  pull_request_target:

jobs:
  build-and-test:
    name: Run Shared Build and Test Workflow
    # Add working-directory here to ensure the job starts at the repository root
    runs-on: ubuntu-latest # You might need to add this line if it's not inherited
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        run: dotnet build && dotnet test